### ISSUE TITLE
empty AA_CNV_SEEDS.bed file

### ISSUE THREAD

**Issue by gneedle1** [jluebeck/AmpliconSuite-pipeline#24]
The program seems to run fine, but my AA_CNV_SEEDS.bed file allways comes out empty.

**Comment by jluebeck** [comment]
Hi, 

The seeds file will be empty if there are no candidate focal amplification regions detected in your sample. If you think that occurred erroneously (that there are focal amplifications), let me know and we can determine how to debug your case.

Jens

**Comment by gneedle1** [comment]
I know there is definitely a duplication of one gene, is that enough? I am just tryin to see if I can get the program to work before using actual data so this is just some test WGS I already had. Would I still be able to test run Amplicon Architect with an empty  AA_CNV_SEEDS.bed file?

**Comment by jluebeck** [comment]
Hi, we do not consider simple gene duplication events to necessarily be focal amplifications on their own, so it is unlikely the tool would put such events into the seeds file.

Here is a good testing dataset for AA: https://www.ncbi.nlm.nih.gov/sra/SRX5055022[accn]. It is GBM39, an ecDNA+ cell-line that appeared in the Wu et al. 2019 and Turner et al. 2017 Nature publications.

Jens

**Comment by gneedle1** [comment]
Okay, perfect, I will try it out. Thank you for your help!
