### ISSUE TITLE
AA error in insert_sdevs

### ISSUE THREAD

**Issue by Tina04021997** [jluebeck/AmpliconSuite-pipeline#27]
Hi, 

Thank you for your work!
While I was trying to run AA by applying PAA, I ran into the error message:
AmpliconArchitect.py: error: unrecognized arguments: --insert_sdevs 3.0

I used the following commend:
$PAA/PrepareAA.py -s $sample -t 20 -o $outputfile --ref GRCh38 --python3_path /home/tiy002/anaconda3/envs/pAA/bin/python3 --aa_python_interpreter /home/tiy002/anaconda3/envs/AA/bin/python2.7 --cnv_bed $CNV_CALLS.bed --sorted_bam $sample.bam --cngain 4.3 --cnsize_min 50000 --run_AA

When I tried to add the parameter --AA_insert_sdevs 3.0 and ran PAA again, the same error still occurs. 
I have upgraded all AA, PAA, AC before sending the job to the latest version and I wonder what else do you suggest me to adjust. Thank you!

**Comment by jluebeck** [comment]
Hi Tina,

Thanks for reaching out about this. This error could happen for a couple of reasons:

1) Not using the jluebeck AA fork. (Also check your $AA_SRC variable to ensure it is pointing to the correct place).
2) The version of AA is outdated (1.2 or earlier). Once you've confirmed that you are using the jluebeck fork, please pull the latest version and try running PAA again. If issues persist, please let me know!

Jens

**Comment by Tina04021997** [comment]
Problem solved! Thank you, Jens.
Also, I would like to ask: I was working on creating union seeds across all relevant samples in the same patient, and I realized the CNV_CALLS.bed were not been filtered (the cngain threshold has not been applied). The CNV_SEEDS.bed was filtered. 
I wonder if I have to apply additional filtering steps.
Thank you.

**Comment by jluebeck** [comment]
Hi Tina,

To create a set of union seeds, please merge from the AA_CNV_SEEDS.bed files, and assign an arbitrary copy-number in the last column, then feed into PrepareAA when running each individual sample from that group. Note that the merged file should still end with "_AA_CNV_SEEDS.bed". I have added a brief explanation of the multi-sample merging procedure to the [GUIDE.md](https://github.com/jluebeck/AmpliconSuite-pipeline/blob/master/GUIDE.md) file in the latest update.

Thanks,
Jens

**Comment by Tina04021997** [comment]
Understood! Thank you!
