### ISSUE TITLE
Missing seed_trimmer.py in the scripts directory

### ISSUE THREAD

**Issue by solo7773** [jluebeck/AmpliconSuite-pipeline#36]
Hi Jens,

Yesterday I updated from 0.13x to 0.1477, but there is no **seed_trimmer.py** any longer in the scripts directory. According to GUIDE.md, this script can filter CNV segments > 10 Mbp.

Unfortunately, I have deleted all the 0.13x files. Since I implement the AA pipeline manually myself, could you add the script back to the repository, or provide a workaround?

Many thanks,
Nan

**Comment by jluebeck** [comment]
Hi Nan,

The older versions of PrepareAA can be accessed by visiting the [version history of the repo on GitHub](https://github.com/jluebeck/AmpliconSuite-pipeline/commits/master), or from the [previous docker images] (https://hub.docker.com/repository/docker/jluebeck/prepareaa/general).

Please keep in mind though that the reason we no long provide the standalone script is that there is a module now embedded with PrepareAA.py to handle these cases by default, and also improve filtering of arm-level chromosomal abnormalities which are likely not real focal amps. We believe the current solution in 0.1477 is better than what was presented in 0.13xx.

Thanks,
Jens

**Comment by solo7773** [comment]
Hi Jens,

Thank you very much. I see. I will use the 0.1477 now.

Best wishes,
Nan
